"""In this module, we configure stuff."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/01_configuration.ipynb.

# %% auto 0
__all__ = ['config', 'Config']

# %% ../nbs/01_configuration.ipynb 4
from pathlib import Path
import thucy
from dotenv import set_key, load_dotenv, dotenv_values

# %% ../nbs/01_configuration.ipynb 6
class Config:
    """Global configuration for the thucy project"""

    DEFAULTS = {
        "EXPERTS_MODEL": "gpt-5-mini",
        "LEAD_MODEL": "gpt-5",
        "SQL_EXPERT_MAX_TURNS": 30,
        "SCHEMA_EXPERT_MAX_TURNS": 30,
        "DATA_EXPERT_MAX_TURNS": 30,
        "GENAI_SERVER_URL": "http://127.0.0.1:5000",
    }
    
    def __init__(self):
        # Path Configs
        self.project_root = Path(thucy.__file__).parent.parent
        self.expertiments_dir = self.project_root / "experiments"
        self.results_dir = self.expertiments_dir / "results"  

        self.env_path = self.project_root / ".env"
        self.env_path.touch(exist_ok=True)

        # Load environment variables
        self._load_env()

    def _load_env(self):
        """Load everything in DEFAULTS + everything in the .env file."""
        # Load into the environment to make sure
        load_dotenv(self.env_path, override=True)

        env = dotenv_values(self.env_path)

        # defaults
        for key, default in self.DEFAULTS.items():
            val = env.get(key, default)
            if val.isdigit(): setattr(self, key.lower(), int(val))
            else: setattr(self, key.lower(), val)

        # user-defined keys (e.g., OPENAI_API_KEY)
        for key, val in env.items():
            if key not in self.DEFAULTS:
                if val.isdigit(): setattr(self, key.lower(), int(val))
                else: setattr(self, key.lower(), val)

    def set_env_var(self, key, value):
        """Set or update a variable and persist to .env."""
        value = str(value)
        set_key(self.env_path, key, value)
        setattr(self, key.lower(), value)
        self._load_env()

# %% ../nbs/01_configuration.ipynb 8
config = Config()
