"""In this module, we configure stuff."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/00_config.ipynb.

# %% auto 0
__all__ = ['config', 'Config', 'set_project_env_variable']

# %% ../nbs/00_config.ipynb 3
from pathlib import Path
import thucy

# %% ../nbs/00_config.ipynb 4
class Config:
    """Global configuration for the thucy project"""
    
    def __init__(self):
        # Path Configs
        self.project_root = Path(thucy.__file__).parent.parent
        self.expertiments_dir = self.project_root / "experiments"
        self.results_dir = self.expertiments_dir / "results"
        
        # Agentic Configs
        self.experts_model = "gpt-5-mini"
        self.lead_model = "gpt-5"
        
        # Max turns
        self.sql_expert_max_turns = 30
        self.schema_expert_max_turns = 30
        self.data_expert_max_turns = 30
        
        # MCP ToolBox
        self.genai_server_url = "http://127.0.0.1:5000"

# %% ../nbs/00_config.ipynb 5
config = Config()

# %% ../nbs/00_config.ipynb 7
from dotenv import set_key

# %% ../nbs/00_config.ipynb 8
def set_project_env_variable(name: str, key: str):
    """Sets an environment variable for the project and saves it to the project .env file."""
    env_path = config.project_root / ".env"
    
    # Create file if it doesn't exist
    if not env_path.exists():
        env_path.touch()
    
    # This handles overwriting automatically
    set_key(env_path, name, key)
