"""Here, we will define the main functionalities of the package."""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_main.ipynb.

# %% auto 0
__all__ = ['handle_config_command', 'main']

# %% ../nbs/04_main.ipynb 3
import argparse
from .configuration import *

def handle_config_command(args):
    if args.config_action == 'set':
        config.set_env_var(args.key, args.value)
    elif args.config_action == 'show':
        config.show_config()
    else:
        print("Use: thucy config [set|show]")

def main():
    parser = argparse.ArgumentParser(description='Thucy CLI')
    subparsers = parser.add_subparsers(dest='command', help='Commands')
    
    # Config command
    config_parser = subparsers.add_parser('config', help='Manage configuration')
    config_subparsers = config_parser.add_subparsers(dest='config_action')
    
    # thucy config set KEY VALUE
    set_parser = config_subparsers.add_parser('set', help='Set a config value')
    set_parser.add_argument('key', help='Config key (e.g., OPENAI_API_KEY)')
    set_parser.add_argument('value', help='Config value')
    
    # thucy config list
    config_subparsers.add_parser('show', help='List available keys')
    
    args = parser.parse_args()
    
    if args.command == 'config':
        handle_config_command(args)

# %% ../nbs/04_main.ipynb 4
try: from nbdev.imports import IN_NOTEBOOK
except: IN_NOTEBOOK=False

# %% ../nbs/04_main.ipynb 5
if __name__ == '__main__' and not IN_NOTEBOOK:
    main()
