"""In this module, we"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/04_toolbox.ipynb.

# %% auto 0
__all__ = ['genai_mcp', 'GenAIToolboxMCP']

# %% ../nbs/04_toolbox.ipynb 3
from toolbox_core import ToolboxSyncClient
from agents import function_tool
from .configuration import config

# %% ../nbs/04_toolbox.ipynb 4
class GenAIToolboxMCP:
    """Factory for managing a shared ToolboxSyncClient and loading toolsets."""
    def __init__(self):
        self.toolset = None

    def set_specific_toolset(self, toolset: str):
        self.toolset = toolset

    def load_toolset(self, toolset_name: str):
        """Load a toolset by name and wrap it with openai sdk tool tool func."""

        # If a specific database is set, modify the toolset name accordingly.
        # This allows for specific database toolsets to be loaded, instead
        # of the "big" generic ones.
        if self.toolset:
            toolset_name = f"{self.toolset}-{toolset_name}"

        toolset = self.client.load_toolset(toolset_name)

        return [function_tool(tool) for tool in toolset]
    
    def connect(self):
        self.client = ToolboxSyncClient(config.genai_server_url)
    
    def close(self):
        self.client.close()

# %% ../nbs/04_toolbox.ipynb 5
genai_mcp = GenAIToolboxMCP()
